booking_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from personal.views import (
    home_screen_view,
)
from history.views import (
    history_view,
)
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls')),
    path('history/', include('history.urls')),
    path('', home_screen_view, name="home"),
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    path('history/', history_view, name="history"),





    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
        name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
        name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_summary, name="cart_summary"),
    path('add/', views.cart_add, name="cart_add"),
    path('delete/', views.cart_delete, name="cart_delete"),
    path('update/', views.cart_update, name="cart_update"),
    path('orders/', views.orders, name="orders"),
    path('booking/', views.booking_page, name="booking_page"),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
import personal.views
import store.views


app_name = 'store'

urlpatterns = [
    path('', views.main_store, name='main_store'),
    path('item/<slug:slug>/', views.offer_detail, name="offer_detail"),
    path('search/<slug:category_slug>/', views.category_list_view, name="category_list_view"),
    path('ajax-add-review/<id>', views.ajax_add_review, name="ajax-add-review"),
    path('search/', views.search, name="search"),
    path('filter-items/', views.filter_items, name="filter-items"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models
from store.models import Offer
from account.models import User


class Booking(models.Model):
    offer = models.ForeignKey(Offer, on_delete=models.CASCADE, related_name="booking")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    booking_date = models.DateTimeField(auto_now_add=True)
    checkin_date = models.DateField()
    checkout_date = models.DateField()
    class Meta:
        ordering = ('-booking_date',)


store/models.py
from django.db import models
from account.models import User
from django.core.validators import MinValueValidator, MaxValueValidator, URLValidator
from django.urls import reverse

PERIODS = [
    ("D", "per day"),
    ("W", "per week"),
    ("M", "per month"),
]

RATING = [
    (1, "★☆☆☆☆"),
    (2, "★★☆☆☆"),
    (3, "★★★☆☆"),
    (4, "★★★★☆"),
    (5, "★★★★★"),
]


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'
        ordering = ('name',)

    def get_absolute_url(self):
        return reverse('store:category_list_view', args=[self.slug])

    def __str__(self):
        return self.name

class Owner(models.Model):
    owner_name = models.CharField(max_length=255, unique=True)
    location = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField(null=True, blank=True)
    rating = models.FloatField(null=True, default=0)

    class Meta:
        verbose_name_plural = 'owners'
        ordering = ('owner_name',)

    def __str__(self):
        return self.owner_name


class Offer(models.Model):
    category = models.ForeignKey(Category, related_name='offer', on_delete=models.CASCADE)
    owned_by = models.ForeignKey(Owner, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    location = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(1)])
    rating = models.FloatField(null=True, default=0)

    period = models.CharField(max_length=10, choices=PERIODS, default='D')
    room_type = models.CharField(max_length=50)
    picture = models.ImageField(upload_to='images/')
    created = models.DateTimeField(auto_now_add=True)
    description = models.TextField(null=True, blank=True)
    is_available = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'offers'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:offer_detail', args=[self.slug])

    def serialize(self):
        return {
            'id': self.pk,
            'category': self.category.name,
            'owned_by': self.owned_by.owner_name,
            'name': self.name,
            'slug': self.slug,
            'location': self.slug,
            'price': self.price,
            'is_available': self.is_available,
            'is_active': self.is_active,
            'period': self.period,
            'room_type': self.room_type,
            'picture': self.picture,
            'created': self.created,
            'description': self.description,

        }

    def __str__(self):
        return self.name


class Review(models.Model):
    offer = models.ForeignKey(Offer, on_delete=models.CASCADE, related_name="reviews")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating_value = models.IntegerField(choices=RATING, default=None)
    created_date = models.DateTimeField(auto_now_add=True)
    edited_date = models.DateTimeField(auto_now=True)
    review_text = models.TextField(null=True, blank=True)


    class Meta:
        verbose_name_plural = 'reviews'
        ordering = ('-created_date',)

    def __str__(self):
        return self.offer.name

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .cart import Cart
from .models import Booking
from history.models import ViewHistory
from store.models import Offer
import json
from django.http import JsonResponse
from django.contrib import messages


def cart_summary(request):
    cart = Cart(request)
    cart_items = cart.get_items
    quantities = cart.get_quants
    totals = cart.cart_total()

    context = {
        'cart_items': cart_items,
        'quantities': quantities,
        'totals': totals,
    }
    return render(request, "cart/cart_summary.html", context)

def cart_add(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        offer_id = int(request.POST.get('offer_id'))
        offer_qty = int(request.POST.get('offer_qty'))
        offer = get_object_or_404(Offer, id=offer_id)
        cart.add(offer=offer, quantity=offer_qty)
        cart_count = cart.__len__()
        response = JsonResponse({
            'count': cart_count,
        })
        messages.success(request, ("Product added to cart"))
        return response



def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        offer_id = int(request.POST.get('offer_id'))
        cart.delete(offer=offer_id)
        response = JsonResponse({
                'offer': offer_id
            })
        return response
def cart_update(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        offer_id = int(request.POST.get('offer_id'))
        offer_qty = int(request.POST.get('offer_qty'))

        cart.update(offer=offer_id, quantity=offer_qty)
    response = JsonResponse({
        'count': offer_qty
    })
    return response


def orders(request):
    if request.method == 'POST':
        items = json.loads(request.POST.get('items'))

        for item in items:
            offer_id = item['offer_id']
            checkin_date = item['checkin_date']
            checkout_date = item['checkout_date']
            cart = Cart(request)

            Booking.objects.create(
                offer_id=offer_id,
                user=request.user,
                checkin_date=checkin_date,
                checkout_date=checkout_date
            )
            cart.delete(offer=offer_id)

        return JsonResponse({'status': 'success'})
    else:
        return JsonResponse({'status': 'error'})


def booking_page(request):
    orders = Booking.objects.filter(user=request.user)
    history = ViewHistory.objects.filter(user=request.user).order_by('-view_date')[:5]
    context = {
        'history': history,
        'orders': orders,
    }
    return render(request, 'cart/orders.html', context)

cart/templates/cart/cart_summary.html
{% extends 'base.html'%}
{% block content %}
    <title>Cart | Dwelly</title>
    <style type="text/css">
        body {
            background: rgb(253,253,201);
            background: linear-gradient(45deg, rgba(253,253,201,1) 30%, rgba(254,238,229,1) 70%);
        }
        .ratings i {
            font-size: 16px;
            color: #a41515;
        }
        #trash-icon:hover {
            color: #a41515;
        }
        .strike-text{
            color: red;
            text-decoration: line-through;
        }
        .product-image{
            width: 100%;
        }
        .main-card {
            border-radius: 4vh;
        }
        .product-card h4, .product-card p, .rate-text {
            color: #441212;
        }
        .btn-add {
            color: #340d0d;
            border-radius: 3vh;
            transition-duration: 0.3s;
            border: solid 1px #340d0d;
        }
        .btn-add:hover, .btn-add:focus {
            background-color: #340d0d;
            color: #feeee5;
            transition-duration: 0.3s;
            box-shadow: none;
        }
        .card {
            border: none;
            border-radius: 3vh;
        }
        .btn-details {
            background-color: #f06d22;
            color: #feeee5;
            border-radius: 3vh;
            transition-duration: 0.5s;
        }
        .product-image{
            width: 100%;
            border-radius: 3vh;
            transition-duration: 0.5s;
        }
        .product-image:hover {
            box-shadow: 3px 4px 0px #ffcaab;
            transition-duration: 0.5s;
        }
        .product-header {
            color: #340d0d;
            font-weight: 500;
        }
        .dot{
            height: 7px;
            width: 7px;
            margin-left: 6px;
            margin-right: 6px;
            margin-top: 3px;
            background-color: #a41515;
            border-radius: 50%;
            display: inline-block;
        }
        .spec-1{
            color: #938787;
            font-size: 15px;
        }
        h5{
            font-weight: 400;
        }
        .para{
            font-size: 16px;
        }

        .btn-details:hover, .btn-details:focus {
            background-color: #ffcaab;
            color: #f06d22;
            transition-duration: 0.5s;
            box-shadow: none;
        }
    </style>

    <svg xmlns="http://www.w3.org/2000/svg"  style="display: none;">
        <symbol id="trash" viewBox="0 0 16 16">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
        </symbol>
    </svg>
    <div class="container">
        {% if cart|length != 0 %}

    {% for item in cart_items %}
        <div class="d-flex justify-content-center row">
                <div class="col-md-10 product-card">
                    <div class="row p-2 bg-white main-card mt-2 mb-2">
                        <div class="col-md-3 mt-1">
                            <a href="{{ item.get_absolute_url }}"><img class="img-fluid img-responsive product-image" src="{{ item.picture.url }}"></a>
                        </div>
                        <div class="col-md-6 mt-1">
                            <a class="text-dark text-decoration-none" href="{{ item.get_absolute_url }}"><h5>{{ item.name }}</h5></a>
                            <div class="mt-1 mb-1 spec-1"><span>{{ item.category|title }}</span></div>
                            <div class="mt-1 mb-1 spec-1"><span>{{ item.owned_by.owner_name }}</span><span class="dot"></span><span>{{ item.location }}</span><span class="dot"></span><span>{{ item.room_type }}<br></span></div>


                            <div class="d-flex flex-row align-items-center mt-3">
                                <div class="col-md-8 d-flex row">
                                    <input type="hidden" name="offer_id" value="{{ item.id }}">
                                    <input type="date" class="checkin_date col-md-4 form-control" placeholder="Check-in date" >
                                    <input type="date"  class="checkout_date col-md-3 form-control" placeholder="Checkout date" >
                                </div>
                            </div>
                        </div>
                        <div class="align-items-center align-content-center col-md-3 border-left mt-1">
                            <div class="col-md-12 row d-flex">
                                <div class="col-md-6 d-flex flex-row align-items-center">
                                    <h4 class="mr-1">${{ item.price }}</h4><span class="mx-2 text-muted fw-light">total</span>
                                </div>
                                <div class="col-md-3 offset-3 text-center">
                                    <a href="#" role="button" data-index="{{ item.id }}" class="nav-link text-dark delete-cart">
                                        <svg class="bi d-block bi-trash ms-2" id="trash-icon" width="24" height="24"><use xlink:href="#trash"/></svg>
                                    </a>
                                </div>
                            </div>
                                <div class="d-flex flex-column mt-4">
                                    <a class="btn btn-details book-btn btn-sm" href="#" data-index="{{ item.id }}" role="button">Book it</a>
                                    <button class="btn btn-add btn-sm mt-2 update-cart" data-index="{{ item.id }}" type="button">Update</button>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
    {% endfor %}

        <div class="offset-2 col-md-10">
            <div class="col-md-3 mb-4">
                <h3 class="d-block">Total:  <span class="h4">  ${{ totals }}</span></h3>
            </div>
            <div>
                <button id="book-all-btn" class="btn btn-details p-3 btn-lg booking-btn">Book all</button>
            </div>
        </div>
    </div>
        {% else %}
            <div class="jusify-content-center m-auto" style="height: 100vh;">
                <div class="text-center">
                    <h3>Your cart is empty, no orders yet.<br>Would you like to <a class="text-danger text-decoration-none" href="{% url 'store:main_store' %}">book anything</a>?</h3>
                </div>
            </div>
        {% endif %}


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).on('click', '.update-cart', function (e) {
            e.preventDefault();
            var offer_id = $(this).data('index');

            $.ajax({
                type: 'POST',
                url: '{% url 'cart_update' %}',
                data: {
                    offer_id: $(this).data('index'),
                    offer_qty: $('#select' + offer_id + ' option:selected').text(),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'post'
                },
                success: function (json){
                    //console.log(json)
                    document.getElementById("cart-count").
                        textContent = json.count
                    location.reload()
                },
                error: function (xhr, errmsg, err) {

                }
            });
        });


        $(document).on('click', '.delete-cart', function (e) {
            e.preventDefault();
            var offer_id = $(this).data('index');

            $.ajax({
                type: 'POST',
                url: '{% url 'cart_delete' %}',
                data: {
                    offer_id: $(this).data('index'),
                    offer_qty: $('#select' + offer_id + ' option:selected').text(),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'post'
                },
                success: function (json){
                    location.reload()
                },
                error: function (xhr, errmsg, err) {

                }
            });
        });



        $(document).on('click', '#book-all-btn', function(e) {
            e.preventDefault();
            var items = [];

            $('.product-card').each(function() {
                var offer_id = $(this).find('[name="offer_id"]').val();
                var checkin_date = $(this).find('.checkin_date').val();
                var checkout_date = $(this).find('.checkout_date').val();

                var today = new Date();
                var checkin = new Date(checkin_date);
                var checkout = new Date(checkout_date);

                if (checkin < today || checkout < today) {
                    alert('The check-in or check-out date cannot be earlier than todays date.');
                    return;
                }

                if (checkout <= checkin) {
                    alert('The checkout date must be after the check-in date.');
                    return;
                }

                items.push({
                    'offer_id': offer_id,
                    'checkin_date': checkin_date,
                    'checkout_date': checkout_date
                });
            });

            $.ajax({
                type: 'POST',
                url: '{% url 'orders' %}',
                data: {
                    'items': JSON.stringify(items),
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(json) {
                    location.reload();
                },
                error: function(xhr, errmsg, err) {
                    alert('Error occurred while booking items.');
                }
            });
        });
    </script>
{% endblock content %}

cart/templates/cart/orders.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style type="text/css">
    .history-card, .order-card {
        height: 100%;
    }
    .history-card img  {
        max-height: 120px;
    }
</style>
    <body>
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
              <symbol id="history" viewBox="0 0 16 16">
                  <path d="M8.515 1.019A7 7 0 0 0 8 1V0a8 8 0 0 1 .589.022zm2.004.45a7 7 0 0 0-.985-.299l.219-.976q.576.129 1.126.342zm1.37.71a7 7 0 0 0-.439-.27l.493-.87a8 8 0 0 1 .979.654l-.615.789a7 7 0 0 0-.418-.302zm1.834 1.79a7 7 0 0 0-.653-.796l.724-.69q.406.429.747.91zm.744 1.352a7 7 0 0 0-.214-.468l.893-.45a8 8 0 0 1 .45 1.088l-.95.313a7 7 0 0 0-.179-.483m.53 2.507a7 7 0 0 0-.1-1.025l.985-.17q.1.58.116 1.17zm-.131 1.538q.05-.254.081-.51l.993.123a8 8 0 0 1-.23 1.155l-.964-.267q.069-.247.12-.501m-.952 2.379q.276-.436.486-.908l.914.405q-.24.54-.555 1.038zm-.964 1.205q.183-.183.35-.378l.758.653a8 8 0 0 1-.401.432z"/>
                  <path d="M8 1a7 7 0 1 0 4.95 11.95l.707.707A8.001 8.001 0 1 1 8 0z"/>
                  <path d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5"/>
              </symbol>
        </svg>
        <div class="container">


        <div class="col-md-12 d-flex justify-content-center my-2">
            <h2>Your last orders:</h2>
        </div>

            <div class="col-md-12 order-list row d-flex">
                {% for order in orders %}
                <div class="col-md-3 product-card {% if forloop.counter > 4 %}d-none{% endif %}">
                            <div class="row p-2 bg-card border order-card rounded mt-2 mb-1">
                                <a href="#"><img class="img-fluid img-responsive rounded product-image" href="{{ order.offer.get_absolute_url }}" src="{{ order.offer.picture.url }}"></a>
                                <div class="col-md-12 mt-1">
                                    <h5>{{ order.offer.name }}</h5>
                                    <div class="d-flex flex-row">
                                    </div>
                                    <div class="mt-1 mb-1 spec-1"><span>{{ order.checkin_date|date:"d M, Y" }}-{{ order.checkout_date|date:"d M, Y" }}</span><span class="dot"></span><br><span> {{ order.offer.category|title }}</span></div>
                                    <div class="mt-1 mb-1 spec-1"><span>{{ order.offer.owned_by }}</span></div>
                                </div>
                                <div class="align-items-center align-content-center col-md-12 border-left mt-1">
                                    <div class="d-flex flex-row align-items-center mb-1">
                                        <h4 class="col-md-3">${{ order.offer.price }}  </h4><span class="mx-2 col-md-5 ps-3 text-muted fw-light">{{ order.offer.get_period_display }}</span>
                                        <div class="ratings col-md-4 pe-3 text-end mt-1">3.9<i class="fa fa-star"> </i></div>
                                    </div>
                                        {% if user.is_authenticated %}
                                            <form action="/history/" method="POST">{% csrf_token %}
                                                <input type="hidden" name="id" value="#">
                                                <a href="" role="button"><button class="btn btn-danger btn-sm w-100"> Details</button> </a>
                                            </form>
                                        {% endif %}
                                </div>
                            </div>
                        </div>
                {% endfor %}
            <div class="justify-content-center d-flex row my-3 px-2">
                <div class="col-md-3 my-3">
                    <div class="col-md-12 m-auto justify-content-center d-flex row">
                        <button class="btn btn-danger w-10" id="show-more-btn">Show More</button>
                    </div>
                    <div class="col-md-12 m-auto justify-content-center d-flex row">
                        <button class="btn btn-danger w-10" id="show-less-btn">Show Less</button>
                    </div>
                </div>
            </div>
            </div>


        <div class="col-md-12 d-flex history-block justify-content-between row my-4 px-4">
                {% for item in history %}
                <div class="col-md-2 mx-1 product-card">
                            <div class="row py-2 bg-card border rounded history-card mt-2 mb-1">
                                <div class="justify-content-center m-auto col-md-12 d-flex ">
                                   <img class="img-fluid w-100 img-responsive rounded product-image" src="{{ item.offer.picture.url }}">
                                </div>
                                <div class="col-md-12 mt-1">
                                    {% if item.offer.name|length > 18 %}
                                        <h6>{{ item.offer.name|title|slice:18}}...</h6>
                                    {% else %}
                                        <h6>{{ item.offer.name|title}}</h6>
                                    {% endif %}
                                    <div class="d-flex flex-row">
                                    </div>
                                    <div class="mt-1 mb-1 spec-1"><span>Visited: {{ item.view_date|date:"d M, Y"  }}</span><span class="dot"></span><br><span>{{ item.offer.category|title }}</span></div>
                                </div>
                                <div class="align-items-center align-content-center col-md-12 border-left mt-1">
                                    <div class="d-flex flex-row align-items-center mb-1">
                                        <div class="ratings col-md-4 pe-3 text-end mt-1">{{ item.offer.rating }}<i class="fa fa-star"> </i></div>
                                    </div>
                                        {% if user.is_authenticated %}
                                            <form action="/history/" method="POST">{% csrf_token %}
                                                <input type="hidden" name="id" value="{{ item.offer.id }}">
                                                <a href="{{ item.offer.get_absolute_url }}" role="button"><button class="btn btn-danger btn-sm w-100"> Details</button> </a>
                                            </form>
                                        {% endif %}
                                </div>
                            </div>
                    </div>
                {% endfor %}
                <div class="col-md-1 my-auto">
                    <a href="{% url 'all_history' %}" role="button" class="nav-link logout-btn">
                        <svg class="bi d-block mx-auto mb-1" width="30" height="30"><use xlink:href="#history"/></svg>
                        <small>History</small>
                    </a>
                </div>
            </div>

            <div class="col-md-12 mt-4 d-flex history-block justify-content-between row mb-4 px-4">
                <h2 class="text-center">Recommendations for you:</h2>
            </div>
        </div>


                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


        <script>
            $(document).ready(function(){

                $('#show-more-btn').click(function () {
                    $('.order-list .product-card.d-none').removeClass('d-none');
                    $(this).hide();
                    $('#show-less-btn').show();
                });

                $('#show-less-btn').click(function () {
                    $('.order-list .product-card:gt(3)').addClass('d-none');
                    $(this).hide();
                    $('#show-more-btn').show();
                });
                $('#show-less-btn').hide();
            });
        </script>

    </body>

{% endblock content %}